services:
  - type: web
    name: golden-knight-chess-club
    env: node
    buildCommand: npm install && cd web && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chess-club-db
          property: connectionString

databases:
  - name: chess-club-db
    databaseName: chess_club
    user: chess_club_user