services:
  - name: web
    type: web
    env: node
    buildCommand: |
      npm install express@4.18.3 --save
      npm install
      cd web
      npm install
      npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: chess_db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: WS_PATH
        value: /ws
      - key: LOG_LEVEL
        value: info

databases:
  - name: chess_db
    databaseName: chess_club
    user: chess_admin